Azure/AKS-Edge

tools/modules/AksEdgeDeploy/AksEdge-Arc.ps1
tools/modules/AksEdgeDeploy/AksEdgeDeploy.psm1

fix [Feedback] Connect-AideArc . #16

---

tools/scripts/AksEdgeAzureSetup/AksEdgeAzureSetup.ps1
tools/scripts/AksEdgeQuickStart/AksEdgeQuickStart.ps1

QuickStart script that downloads this gitrepo and invokes AksEdgeAzureSetup for quick setup of Azure account and finally downloads, installs and deploys AksEdgeEssentials.

QuickStart script addition

---

tools/scripts/AksEdgeQuickStart/AksEdgeQuickStart.ps1

Fix path used for aksedgeazuresetup

fix path for aksedgeazuresetup

---

tools/modules/AksEdgeDeploy/AksEdgeDeploy-AEC.ps1
tools/modules/AksEdgeDeploy/AksEdgeDeploy.psd1

Add NuGet Provider if not available, for Az Powershell module installation from PSGallery

Nuget install added

---

tools/scripts/AksEdgeQuickStart/AksEdgeQuickStart.ps1
tools/scripts/AksEdgeQuickStart/README.md

ServiceIpRangeSize defined to enable LoadBalancer type services

ServiceIpRangeSize defined to enable LoadBalancer type services

---

tools/modules/AksEdgeDeploy/AksEdgeDeploy-AEC.ps1
tools/modules/AksEdgeDeploy/AksEdgeDeploy.psd1

Fix Initialize-AideArc for Az Modules error counting

Fix Initialize-AideArc for Az Modules error counting

---

tools/modules/AksEdgeDeploy/AksEdgeDeploy-AEC.ps1
tools/modules/AksEdgeDeploy/AksEdgeDeploy.psd1

* Fix Initialize-AideArc for az modules errCnt

Fix Initialize-AideArc for Az Modules error counting (#80)

---

tools/aksedge-config.json
tools/modules/AksEdgeDeploy/AksEdgeDeploy-AEC.ps1
tools/modules/AksEdgeDeploy/AksEdgeDeploy.psd1

0.9.0 intake and removal of patches fixed in this release.

Az ConnectedKubernetes 0.9.0 intake

---

tools/aksedge-config.json
tools/modules/AksEdgeDeploy/AksEdgeDeploy-AEC.ps1
tools/modules/AksEdgeDeploy/AksEdgeDeploy.psd1

* Az ConnectedKubernetes 0.9.0
* remove azure-arc-release patch - 0.9.0 version fix

Az ConnectedKubernetes 0.9.0 intake (#91)

---

README.md

https://github.com/Azure/AKS-Edge/blob/main/README.md 
#PingMSFTDocs

Typo "Github"→"GitHub"

---

tools/modules/AksEdgeDeploy/AksEdgeDeploy.psm1

switch mars invocation based on provider. for non hcs - use ssh.

mars switch based on provider

---

tools/modules/AksEdgeDeploy/AksEdgeDeploy.psm1

fix upgradejson for v1.8

---

tools/modules/AksEdgeDeploy/AksEdgeDeploy.psd1

update version for 1.8 support changes

update AksEdgeDeploy version 1.0.230707 for 1.8

---

tools/scripts/AksEdgeAzureSetup/AksEdgeAzureSetup-Test.ps1
tools/scripts/AksEdgeAzureSetup/AksEdgeAzureSetup.ps1

Updated the permissions checks in AIDE scripts as per the updated Azure policies on RBAC - https://learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments-steps#privileged-administrator-role

Updated permission check for Azure RBAC

---

tools/modules/AksEdgeDeploy/aksedge-dc.puml

Adding the Ip4AddressPrefix parameter

Adding the missing JSON configs

---

tools/modules/AksEdgeDeploy/AksEdgeDeploy.psd1
tools/modules/AksEdgeDeploy/AksEdgeDeploy.psm1

Enable unzip of the windowsnode.zip file and install from local folder/file share

Enable windows install from local share

---

tools/scripts/AksEdgeQuickStart/AksEdgeQuickStart-v2.ps1

Added variation of the QuickStart script to take aide-user and aks-edge config files path's as input parameters.
Fix for bug- https://msazure.visualstudio.com/msk8s/_workitems/edit/25731458

Add new QuickStart script version to take file-path as parameter

---

samples/others/win-sample-aspnetcore.yaml

This will be used in AKS EE Training Modules

Adding aspnetcore app for learnmodule

---

tools/modules/AksEdgeDeploy/AksEdgeDeploy.psm1

fix EdgeConfig version compare logic

fix EdgeConfig version compare logic

---

tools/scripts/AksEdgeQuickStart/AksEdgeQuickStart-v2.ps1
tools/scripts/AksEdgeQuickStart/AksEdgeQuickStart.ps1
tools/scripts/AksEdgeQuickStart/AksEdgeQuickStartForAio.ps1

"Write-Host -Message "Deployment failed" -Category OperationStopped -ForegroundColor Red" does not have -Category argument. 
Use Write-Error instead...

fix Write-Host API usage

---

tools/scripts/AksEdgeQuickStart/AksEdgeQuickStartForAio.ps1

Update min required az-cli version to 2.64.0 and undo the following:
1. connectedk8s extension removal
2. connectedk8s whl download
3. setting $env:HELMREGISTRY

changes targeting M3 - new arc agent, 16G RAM as default

---

tools/scripts/AksEdgeQuickStart/AksEdgeQuickStartForAio.ps1

Set AKSEE default version to K3s-1.29.6-1.9.262.0 for AIO

update AIO script to pull AKSEE 1.9.262 version

---

tools/scripts/AksEdgeKeyManagerExtension/README.md
tools/scripts/AksEdgeKeyManagerExtension/UpdateK3sConfigForKeyManager.ps1

Add a new script UpdateK3sConfigForKeyManager.ps1 to prepare the K3s cluster for Key Manager extension

add keymanger  script

---

tools/scripts/AksEdgeQuickStart/AksEdgeQuickStartForAio.ps1

Remove k8s (unsupported) option for AIO

remove k8s option for AIO

---

tools/scripts/AksEdgeQuickStart/AksEdgeQuickStartForAio.ps1

proceed with AIO Deployment only if AKSEE K8s is not already installed

proceed with AIO Deployment only if AKSEE K8s is not already installed

---

tools/scripts/AksEdgeAzureSetup/AksEdgeAzureSetup.ps1
tools/scripts/AksEdgeQuickStart/AksEdgeQuickStart.ps1

Update the supported ARC locations

Update supported ARC locations

---

tools/scripts/AksEdgeQuickStart/AksEdgeQuickStartForAio.ps1

set KUBECTL_CLIENT_PATH with kubectl.exe from AKSEE deployment

set KUBECTL_CLIENT_PATH with kubectl.exe from AKSEE deployment

---

tools/modules/AksEdgeDeploy/AksEdgeDeploy-AEC.ps1
tools/modules/AksEdgeDeploy/AksEdgeDeploy.psd1

remove update tag as its done in AKSEE

---

tools/scripts/AksEdgeQuickStart/AksEdgeQuickStartForAio.ps1

update AIO QuickScript to use Feb-Rel-k3s-1.30.6

update AIO QuickScript to use Feb-Rel-k3s-1.30.6

---

tools/modules/AksEdgeDeploy/AksEdge-Arc.ps1
tools/modules/AksEdgeDeploy/AksEdgeDeploy-AES.ps1
tools/modules/AksEdgeDeploy/AksEdgeDeploy.psm1
tools/scripts/AksEdgeAzureSetup/AksEdgeAzureSetup-Test.ps1
tools/scripts/AksEdgeAzureSetup/AksEdgeAzureSetup.ps1
tools/scripts/AksEdgeAzureSetup/InstallArcForServer.ps1
tools/scripts/AksEdgeQuickStart/AksEdgeQuickStart-v2.ps1
tools/scripts/AksEdgeQuickStart/README.md
tools/scripts/AksEdgeRemoteDeploy/AksEdgeRemoteDeploy-Intune.ps1
tools/scripts/AksEdgeRemoteDeploy/AksEdgeRemoteDeploy.ps1

Related to #231 
Fixing all Invoke-WebRequest with the -UseBasicParsing flag

-UseBasicParsing for all iwr

---

tools/AksEdgeShell.ps1
tools/aio-aide-userconfig.json
tools/aio-aksedge-config.json
tools/modules/AksEdgeDeploy/AksEdgeDeploy.psm1
tools/scripts/AksEdgeQuickStart/AksEdgeQuickStartForAio.ps1

1. Accept configuration changes as file input
2. Better error handling
3. sample aide config files for AIO
Verified both
1. AksEdgeQuickScript.ps1
2. AksEdgeQuickScriptForAio.ps1

use file input for configuration changes

---

tools/scripts/AksEdgeQuickStart/AksEdgeQuickStartForAio.ps1

support germanywestcentral for AIO

support germanywestcentral for AIO

---

tools/aio-aide-userconfig.json
tools/aio-aksedge-config.json
tools/aksedge-config.json
tools/modules/AksEdgeDeploy/AksEdgeDeploy.psm1
tools/scripts/AksEdgeQuickStart/AksEdgeQuickStartForAio.ps1

Skip signature check is failing so reverting the changes for now

revert the aio changes

---

tools/aio-aide-userconfig.json
tools/aio-aksedge-config.json
tools/aksedge-config.json
tools/modules/AksEdgeDeploy/AksEdgeDeploy.psm1
tools/scripts/AksEdgeQuickStart/AksEdgeQuickStartForAio.ps1

aio quickstart changes for 1.11.247.0

---

tools/scripts/AksEdgeQuickStart/AksEdgeQuickStart.ps1

1. Make Arc params mandatory
2. Replace Connect-AideArc with Connect-AideArcKubernetes - since Kuberenetes cluster is already arc connected during AKSEE deployment

modify QuickScript to deploy using latest schema version
